### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Lumio4/Yoga#1]
How do i fix this?

![image](https://user-images.githubusercontent.com/35656492/169681208-1158aef5-ac79-4cad-b1b5-1cb1cf6d2600.png)

**Comment by LumioStudio** [comment]
You require the resource qb-target, maybe download the newest one.

Op zo 22 mei 2022 om 08:03 schreef AndreasFromDanmark <
***@***.***>

**Comment by AndreasFromDanmark** [comment]
@Lumio4 Im already using the newest one. from github

https://github.com/qbcore-framework/qb-target
